name: Python Poetry
description: Sets up a Python environment with Poetry

inputs:
  python-version:
    required: false
    description: Python version
    default: "3.10"
  poetry-version:
    required: false
    description: Poetry version
    default: "1.2.2"

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ inputs.poetry-version }}
    - run: poetry install
      shell: sh
