name: CI
on:
  push:
    branches:
      - "main"
    tags:
      - v*
  pull_request:
    branches:
      - "main"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python-poetry
      - uses: pre-commit/action@v2.0.3
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python-poetry
      - run: poetry run pytest
        env:
          TEST_MODE: "1"
  build-and-push-ecr:
    runs-on: ubuntu-latest
    needs: [run-tests]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@8a84b07f2009032ade05a88a28750d733cc30db1
        with:
          role-to-assume: arn:aws:iam::192824654885:role/github-actions-ecr
          aws-region: eu-west-2
      - uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
        env:
          AWS_REGION: us-east-1
      - run: docker context create builders
      - uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders
      - uses: haya14busa/action-cond@v1
        id: image_tag
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags/') }}
          if_true: ${{ github.ref_name }}
          if_false: ${{ github.sha }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: public.ecr.aws/pyth-network/observer:${{ steps.image_tag.outputs.value }}
